all:
  hosts:
  children:
    VM:
      hosts:
        WEB1:
          ansible_host: 192.168.122.75
        WEB2:
          ansible_host: 192.168.122.188
        BDD:
          ansible_host: 192.168.122.247
    BDD:
      hosts:
        BDD:
          ansible_host: 192.168.122.247
    WEB:
      hosts:
        WEB1:
          ansible_host: 192.168.122.75
        WEB2:
          ansible_host: 192.168.122.188
    LOADBALANCER:
      hosts:
        LOADBALANCER1:
          ansible_host: 192.168.122.75
    HYPERVISOR:
      hosts:
        HYPERVISOR:
          ansible_host: 192.168.122.84
