- hosts: BDD
  tasks:
  - name: bind mysql remote address
    ini_file: 
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      section: mysqld
      option: bind-address
      value: 0.0.0.0
      backup: yes
