- hosts: BDD
  tasks:
  - name: Create a new database with name 'wordpress'
    mysql_db:
      name: wordpress
      state: present 
      login_unix_socket: /var/run/mysqld/mysqld.sock
      login_user: 'root'
      login_password: 'User01001'
